print("Olá Sou seu computador, vamos nos conhercer melhor.")
user = input("Como você se chama? R: ")
print("é um prazer em te conhecer ",user," como gostaria de me chamar ?")
name = input()
print("Apartir de agora eu me chamo ",name," , é um nome muito bom.")
